import cv2 
cap1 = cv2.VideoCapture("/dev/video1")
cap2 = cv2.VideoCapture("/dev/video2")
cap3 = cv2.VideoCapture("/dev/video3")
cap4 = cv2.VideoCapture("/dev/video4")
cap5 = cv2.VideoCapture("/dev/video5")
cap6 = cv2.VideoCapture("/dev/video6")
cap1.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
cap2.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
cap3.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
cap4.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
cap5.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
cap6.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc('M', 'J', 'P', 'G'))
try:print("cap1", cap1.read()[1][0])
except:print("CAP1")
try:print("cap2", cap2.read()[1][0])
except:print("CAP2")
try:print("cap3", cap3.read()[1][0])
except:print("CAP3")
try:print("cap4", cap4.read()[1][0])
except:print("CAP4")
try:print("cap5", cap5.read()[1][0])
except:print("CAP5")
try:print("cap6", cap6.read()[1][0])
except:print("CAP6")

cap1.release()
cap2.release()
cap3.release()
cap4.release()
cap5.release()
cap6.release()