name: Deploy MDK to GitHub Pages Repo

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Clone destination repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.GH_DEPLOY_KEY }}@github.com/openUC2/openUC2.github.io.git ../gh-pages

      - name: Copy files to destination folder
        run: |
          mkdir -p ../gh-pages/docs/10_Misc/01_MultiarrayMicroscope
          cp -r IMAGES ../gh-pages/docs/10_Misc/01_MultiarrayMicroscope/
          cp README.md ../gh-pages/docs/10_Misc/01_MultiarrayMicroscope/index.md

      - name: Commit and push changes
        run: |
          cd ../gh-pages
          git add docs/10_Misc/01_MultiarrayMicroscope
          git commit -m "Deploy MDK on release" || echo "No changes to commit"
          git push
